services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kuaizu-server
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    command: ["./kuaizu-server"]

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kuaizu-admin
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8081:8081"
    command: ["./kuaizu-admin"]
