services:
  kuaizu-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION:-latest}
        COMMIT: ${COMMIT:-none}
    image: kuaizu-server:${VERSION:-latest}
    container_name: kuaizu-api
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    command: ["./kuaizu-server"]

  kuaizu-console:
    image: kuaizu-server:${VERSION:-latest}
    container_name: kuaizu-console
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8081:8081"
    command: ["./kuaizu-admin"]
    depends_on:
      - kuaizu-api
