get:
  tags:
    - Products
  summary: 获取商品列表
  description: 获取所有可购买的商品
  operationId: listProducts
  responses:
    '200':
      description: 成功
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/BaseResponse.yaml
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: ../components/schemas/ProductVO.yaml
