get:
  tags:
    - Products
  summary: 获取商品详情
  operationId: getProductDetail
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
      description: 商品ID
  responses:
    '200':
      description: 成功
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/BaseResponse.yaml
              - type: object
                properties:
                  data:
                    $ref: ../components/schemas/ProductVO.yaml
